question_data = [
        {"category": "Entertainment: Video Games", "type": "multiple", "difficulty": "medium",
         "question": "What engine did the original &quot;Half-Life&quot; run on?", "correct_answer": "GoldSrc",
         "incorrect_answers": ["Source", "Quake", "Unreal"]},
        {"category": "Science & Nature", "type": "multiple", "difficulty": "easy",
         "question": "What is the chemical makeup of water?", "correct_answer": "H20",
         "incorrect_answers": ["C12H6O2", "CO2", "H"]},
        {"category": "Science & Nature", "type": "multiple", "difficulty": "medium",
         "question": "Who developed the first successful polio vaccine in the 1950s?", "correct_answer": "Jonas Salk",
         "incorrect_answers": ["John F. Enders", "Thomas Weller", "Frederick Robbins"]},
        {"category": "History", "type": "multiple", "difficulty": "hard",
         "question": "During the Wars of the Roses (1455 - 1487) which Englishman was dubbed &quot;the Kingmaker&quot;?",
         "correct_answer": "Richard Neville", "incorrect_answers": ["Richard III", "Henry V", "Thomas Warwick"]},
        {"category": "Entertainment: Japanese Anime & Manga", "type": "multiple", "difficulty": "hard",
         "question": "What is the last line muttered in the anime film &quot;The End of Evangelion&quot;?",
         "correct_answer": "&quot;How disgusting.&quot;",
         "incorrect_answers": ["&quot;Idiot, I won&#039;t let you kill me!&quot;", "&quot;Nothing.&quot;",
                               "&quot;Goddammit, Shinji.&quot;"]},
        {"category": "Politics", "type": "multiple", "difficulty": "hard",
         "question": "What is the name of Niccol&ograve; Machiavelli&#039;s work that argued effective leaders needed to crush their opponents at all costs?",
         "correct_answer": "The Prince",
         "incorrect_answers": ["The Rape of Lucrece", "Will to Power", "Love&#039;s Labours Lost"]},
        {"category": "Entertainment: Music", "type": "boolean", "difficulty": "medium",
         "question": "A Facebook campaign placed Rage Against The Machine&#039;s &quot;Killing in the Name Of&quot; as the UK Christmas Number 1 in 2009.",
         "correct_answer": "True", "incorrect_answers": ["False"]},
        {"category": "Entertainment: Music", "type": "multiple", "difficulty": "medium",
         "question": "Rick Astley&#039;s hit song &quot;Never Gonna Give You Up&quot; was released in what year?",
         "correct_answer": "1987", "incorrect_answers": ["1985", "1986", "1988"]},
        {"category": "Science: Computers", "type": "multiple", "difficulty": "medium",
         "question": "What does the &#039;S&#039; in the RSA encryption algorithm stand for?",
         "correct_answer": "Shamir", "incorrect_answers": ["Secure", "Schottky", "Stable"]},
        {"category": "Entertainment: Comics", "type": "multiple", "difficulty": "medium",
         "question": "What&#039;s the weakness of american vampires (Scott Snyder&#039;s American Vampire)?",
         "correct_answer": "Gold", "incorrect_answers": ["Sunlight", "Wood", "Silver"]}
    ]